#' 5 Sample Events generated by ChatGPT 3.5
#' 
#' A set of 5 demo events generated by ChatGPT 3.5 on 13 Apr, 2024.
#' The following field descriptions were also generated in the same session.
#' 
#' @format
#' A data frame with 5 (event) rows and 7 columns:
#' \describe{
#'   \item{event_id}{Unique identifier for the event.}
#'   \item{startDate}{Start date of the event.}
#'   \item{endDate}{End date of the event.}
#'   \item{duration}{Duration of the event.}
#'   \item{event_title}{Title or name of the event.}
#'   \item{event_descr}{Description of the event.}
#'   \item{event_emoji}{Emoji representing the event theme or type.}
#'   \item{event_link}{URL link to the event's website or page.}
#' }
#' 
#' @source https://chat.openai.com/share/c68b7a82-5378-45c8-bf41-7fa134f0b74a
"demo_events_gpt"

#' 10 Overlapping Events
#' 
#' A set of 10 demo events where Events 6,7,8 and 9 overlap, with placeholder details
#' generated using the \link[emoji]{zoo} and \link[lorem]{ipsum}.
#' 
#' @format A data frame with 10 (event) rows and 6 columns:
#' \describe{
#'   \item{event_id}{Unique identifier for the event.}
#'   \item{title}{Plaeholder title for the event}
#'   \item{start}{Start date of the event.}
#'   \item{end}{End date of the event.}
#'   \item{duration}{Duration of the event in days.}
#'   \item{emoji}{Emoji representing the event theme or type.}
#'   \item{details}{Loreum Ipsum placeholder details of the event.}
#' }
#' 
#' @source Package Authors
"demo_events_overlap"